name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - uses: android-actions/setup-android@v3
      - name: Build
        run: |
          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android
          npx cap init KaliMobile com.whw961.kali --web-dir=www
          npx cap add android
          npx cap sync
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: Kali-Mobile-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
